import DashboardLayout from "@/components/DashboardLayout";
import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body>
        <Providers>
          <DashboardLayout>{children}</DashboardLayout>
          <Toaster richColors position="bottom-right" />
        </Providers>
      </body>
    </html>
  );
}
